wif:
  issuer: ${WIF_ISSUER:https://issuer-web}
  audience: ${WIF_AUDIENCE:wif-demo-validator}
  issuer-ca: ${WIF_ISSUER_CA:/oidc/tls.crt}

server:
  port: 8080
  shutdown: graceful

logging:
  level:
    root: INFO
    com.nimbusds: INFO
    ms.rohde.wifpoc: DEBUG
